"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getNativeBinding = getNativeBinding;
var node_module_1 = require("node:module");
var cachedBinding;
function getNativeBinding() {
    if (cachedBinding !== undefined) {
        return cachedBinding;
    }
    var require = (0, node_module_1.createRequire)(import.meta.url);
    // For sdk/native: load the NAPI binding from the package root
    // The index.js is auto-generated by napi-rs and loads the .node file
    try {
        var binding = require("../index.js");
        cachedBinding = binding;
        return cachedBinding;
    }
    catch (error) {
        console.warn("Failed to load native NAPI binding:", error);
        cachedBinding = null;
        return cachedBinding;
    }
}
