packages:
  - codex-cli
  - codex-rs/responses-api-proxy/npm
  - sdk/typescript
  - codex-agents-suite
  - shell-tool-mcp

ignoredBuiltDependencies:
  - esbuild

minimumReleaseAge: 10080

blockExoticSubdeps: true
