/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function clearRegisteredTools(): void

export interface JsToolInvocation {
  callId: string
  toolName: string
  arguments?: string
  input?: string
}

export interface NativeToolInfo {
  name: string
  description?: string
  parameters?: JsonValue
  strict?: boolean
  supportsParallel?: boolean
}

export interface NativeToolResponse {
  output?: string
  success?: boolean
  error?: string
}

export declare function registerTool(info: NativeToolInfo, handler: (arg: JsToolInvocation) => NativeToolResponse): void

export interface RunRequest {
  prompt: string
  threadId?: string
  images?: Array<string>
  model?: string
  sandboxMode?: string
  workingDirectory?: string
  skipGitRepoCheck?: boolean
  outputSchema?: JsonValue
  baseUrl?: string
  apiKey?: string
  linuxSandboxPath?: string
  fullAuto?: boolean
  reviewMode?: boolean
  reviewHint?: string
}

export declare function runThread(req: RunRequest): Promise<Array<string>>

export declare function runThreadStream(req: RunRequest, onEvent: ((err: Error | null, arg: JsonValue) => any)): Promise<void>
