/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class AgentOrchestrator {
  constructor()
  addAgent(id: string, config: AgentConfig): void
  removeAgent(id: string): void
  setViewMode(mode: string): void
  switchToAgent(id: string): void
}

export declare class AgentView {
  constructor(threadId: string, title?: string | undefined | null)
  sendMessage(message: string): void
  receiveMessage(message: string): void
  updateStatus(status: string): void
  appendOutput(output: string): void
}

export declare class LayoutManager {
  constructor()
  setSplit(orientation: string, ratio: number, leftId: string, rightId: string): void
}

export declare class StatusBoard {
  constructor(layout?: string | undefined | null)
  addTextTile(id: string, title: string, value: string): void
  addProgressTile(id: string, title: string, value: number): void
  updateTile(id: string, value: string): void
}

export declare class TuiApp {
  constructor(title?: string | undefined | null, width?: number | undefined | null, height?: number | undefined | null)
  addComponent(id: string, componentType: WidgetType): void
  startTerminal(): void
  stopTerminal(): void
}

export declare class TuiSession {
  wait(): Promise<TuiExitInfo>
  shutdown(): void
  get closed(): boolean
}

export interface AgentConfig {
  name: string
  model?: string
  task?: string
}

export declare function callToolBuiltin(token: string, invocation?: JsToolInvocation): Promise<NativeToolResponse>

export declare function clearRegisteredTools(): void

export declare function cloudTasksApply(taskId: string, diffOverride?: string | undefined | null, baseUrl?: string | undefined | null, apiKey?: string | undefined | null): Promise<string>

export declare function cloudTasksApplyPreflight(taskId: string, diffOverride?: string | undefined | null, baseUrl?: string | undefined | null, apiKey?: string | undefined | null): Promise<string>

export declare function cloudTasksCreate(envId: string, prompt: string, gitRef?: string | undefined | null, qaMode?: boolean | undefined | null, bestOfN?: number | undefined | null, baseUrl?: string | undefined | null, apiKey?: string | undefined | null): Promise<string>

export declare function cloudTasksGetDiff(taskId: string, baseUrl?: string | undefined | null, apiKey?: string | undefined | null): Promise<string>

export declare function cloudTasksList(envFilter?: string | undefined | null, baseUrl?: string | undefined | null, apiKey?: string | undefined | null): Promise<string>

export declare function collectRepoDiffSummary(cwd: string, baseBranchOverride?: string | undefined | null, options?: RepoDiffOptions | undefined | null): Promise<RepoDiffSummary>

export declare function compactThread(req: RunRequest): Promise<Array<string>>

export interface ConversationConfigRequest {
  model?: string
  modelProvider?: string
  oss?: boolean
  sandboxMode?: string
  approvalMode?: string
  workspaceWriteOptions?: WorkspaceWriteOptions
  workingDirectory?: string
  skipGitRepoCheck?: boolean
  baseUrl?: string
  apiKey?: string
  linuxSandboxPath?: string
  reasoningEffort?: string
  reasoningSummary?: string
  fullAuto?: boolean
}

export interface ConversationListPage {
  conversations: Array<ConversationSummary>
  nextCursor?: string
  numScannedFiles: number
  reachedScanCap: boolean
}

export interface ConversationSummary {
  id: string
  path: string
  createdAt?: string
  updatedAt?: string
}

export declare function deleteConversation(req: DeleteConversationRequest): Promise<DeleteConversationResult>

export interface DeleteConversationRequest {
  id: string
  config?: ConversationConfigRequest
}

export interface DeleteConversationResult {
  deleted: boolean
}

export interface Dimensions {
  width: number
  height: number
  x: number
  y: number
}

export declare function emitBackgroundEvent(req: JsEmitBackgroundEventRequest): void

export declare function emitPlanUpdate(req: JsEmitPlanUpdateRequest): void

export declare function ensureTokioRuntime(): void

export declare function evAssistantMessage(id: string, text: string): string

export declare function evCompleted(id: string): string

export declare function evFunctionCall(callId: string, name: string, args: string): string

export declare function evResponseCreated(id: string): string

export declare function fastEmbedEmbed(req: FastEmbedEmbedRequest): Promise<Array<Array<number>>>

export interface FastEmbedEmbedRequest {
  inputs: Array<string>
  batchSize?: number
  normalize?: boolean
  projectRoot?: string
  cache?: boolean
}

export declare function fastEmbedInit(opts: FastEmbedInitOptions): Promise<void>

export interface FastEmbedInitOptions {
  model?: string
  cacheDir?: string
  maxLength?: number
  showDownloadProgress?: boolean
  /** Enable CoreML execution provider for Metal/ANE acceleration on macOS */
  useCoreml?: boolean
  /** Use Apple Neural Engine only (vs ANE + GPU) */
  coremlAneOnly?: boolean
}

export interface ForkRequest {
  threadId: string
  nthUserMessage?: number
  model?: string
  modelProvider?: string
  oss?: boolean
  sandboxMode?: string
  approvalMode?: string
  workspaceWriteOptions?: WorkspaceWriteOptions
  workingDirectory?: string
  skipGitRepoCheck?: boolean
  baseUrl?: string
  apiKey?: string
  linuxSandboxPath?: string
  reasoningEffort?: string
  reasoningSummary?: string
  fullAuto?: boolean
}

export interface ForkResult {
  threadId: string
  rolloutPath: string
}

export declare function forkThread(req: ForkRequest): Promise<ForkResult>

export declare function isTokioRuntimeAvailable(): boolean

export interface JsApprovalRequest {
  type: string
  details?: JsonValue
}

export interface JsEmitBackgroundEventRequest {
  threadId: string
  message: string
}

export interface JsEmitPlanUpdateRequest {
  threadId: string
  explanation?: string
  plan: Array<JsPlanItem>
}

export interface JsModifyPlanRequest {
  threadId: string
  operations: Array<JsPlanOperation>
}

export interface JsPlanItem {
  step: string
  status?: string
}

export interface JsPlanOperation {
  type: string
  item?: JsPlanItem
  index?: number
  updates?: JsPlanUpdate
  newOrder?: Array<number>
}

export interface JsPlanUpdate {
  step?: string
  status?: string
}

export interface JsToolInterceptorContext {
  invocation: JsToolInvocation
  token: string
}

export interface JsToolInvocation {
  callId: string
  toolName: string
  arguments?: string
  input?: string
}

export declare const enum LayoutType {
  Split = 0,
  Tabs = 1,
  Grid = 2,
  Stack = 3
}

export declare function listConversations(req: ListConversationsRequest): Promise<ConversationListPage>

export interface ListConversationsRequest {
  config?: ConversationConfigRequest
  pageSize?: number
  cursor?: string
  modelProviders?: Array<string>
}

export declare function modifyPlan(req: JsModifyPlanRequest): void

export interface NativeToolInfo {
  name: string
  description?: string
  parameters?: JsonValue
  strict?: boolean
  supportsParallel?: boolean
}

export interface NativeToolResponse {
  output?: string
  success?: boolean
  error?: string
}

export declare function registerApprovalCallback(handler: (request: JsApprovalRequest) => boolean | Promise<boolean>): void

export declare function registerTool(info: NativeToolInfo, handler: (call: JsToolInvocation) => NativeToolResponse | Promise<NativeToolResponse>): void

export declare function registerToolInterceptor(toolName: string, handler: (context: JsToolInterceptorContext) => NativeToolResponse | Promise<NativeToolResponse>): void

export interface RepoDiffFileChange {
  path: string
  status: string
  diff: string
  truncated: boolean
  previousPath?: string
}

export interface RepoDiffOptions {
  maxFiles?: number
  diffContextLines?: number
  diffCharLimit?: number
}

export interface RepoDiffSummary {
  repoPath: string
  branch: string
  baseBranch: string
  upstreamRef?: string
  mergeBase: string
  statusSummary: string
  diffStat: string
  recentCommits: string
  changedFiles: Array<RepoDiffFileChange>
  totalChangedFiles: number
}

export declare function resumeConversationFromRollout(req: ResumeFromRolloutRequest): Promise<ForkResult>

export interface ResumeFromRolloutRequest {
  rolloutPath: string
  config?: ConversationConfigRequest
}

export interface ReverieConversation {
  id: string
  path: string
  createdAt?: string
  updatedAt?: string
  headRecords: Array<string>
  tailRecords: Array<string>
  headRecordsToon: Array<string>
  tailRecordsToon: Array<string>
}

export declare function reverieGetConversationInsights(conversationPath: string, query?: string | undefined | null): Promise<Array<string>>

export declare function reverieIndexSemantic(codexHomePath: string, options?: ReverieSemanticSearchOptions | undefined | null): Promise<ReverieSemanticIndexStats>

export declare function reverieListConversations(codexHomePath: string, limit?: number | undefined | null, offset?: number | undefined | null): Promise<Array<ReverieConversation>>

/** Search using blocks from the current ongoing conversation to find similar past sessions */
export declare function reverieSearchByConversation(codexHomePath: string, conversationMessages: Array<string>, options?: ReverieSemanticSearchOptions | undefined | null): Promise<Array<ReverieSearchResult>>

export declare function reverieSearchConversations(codexHomePath: string, query: string, limit?: number | undefined | null): Promise<Array<ReverieSearchResult>>

export interface ReverieSearchResult {
  conversation: ReverieConversation
  relevanceScore: number
  matchingExcerpts: Array<string>
  insights: Array<string>
  rerankerScore?: number
}

export declare function reverieSearchSemantic(codexHomePath: string, contextText: string, options?: ReverieSemanticSearchOptions | undefined | null): Promise<Array<ReverieSearchResult>>

export interface ReverieSemanticIndexStats {
  conversationsIndexed: number
  documentsEmbedded: number
  batches: number
}

export interface ReverieSemanticSearchOptions {
  limit?: number
  maxCandidates?: number
  projectRoot?: string
  batchSize?: number
  normalize?: boolean
  cache?: boolean
  rerankerModel?: string
  rerankerCacheDir?: string
  rerankerMaxLength?: number
  rerankerShowProgress?: boolean
  rerankerBatchSize?: number
  rerankerTopK?: number
}

export declare function runApplyPatch(patch: string): void

export interface RunRequest {
  prompt: string
  inputItems?: JsonValue
  threadId?: string
  images?: Array<string>
  model?: string
  modelProvider?: string
  oss?: boolean
  sandboxMode?: string
  approvalMode?: string
  workspaceWriteOptions?: WorkspaceWriteOptions
  reviewMode?: boolean
  reviewHint?: string
  workingDirectory?: string
  skipGitRepoCheck?: boolean
  outputSchema?: JsonValue
  baseUrl?: string
  apiKey?: string
  linuxSandboxPath?: string
  reasoningEffort?: string
  reasoningSummary?: string
  fullAuto?: boolean
}

export declare function runThread(req: RunRequest): Promise<unknown>

export declare function runThreadStream(req: RunRequest, onEvent: (err: unknown, eventJson?: string) => void): Promise<unknown>

export declare function runTui(req: TuiRequest): Promise<TuiExitInfo>

export declare function sse(events: Array<string>): string

export declare function startTui(req: TuiRequest): TuiSession

export interface TokenizerBaseOptions {
  model?: string
  encoding?: "o200k_base" | "cl100k_base"
}

export declare function tokenizerCount(text: string, options?: TokenizerBaseOptions | undefined | null): number

export declare function tokenizerDecode(tokens: Array<number>, options?: TokenizerBaseOptions | undefined | null): string

export declare function tokenizerEncode(text: string, options?: TokenizerEncodeOptions | undefined | null): Array<number>

export interface TokenizerEncodeOptions {
  model?: string
  encoding?: "o200k_base" | "cl100k_base"
  withSpecialTokens?: boolean
}

export interface TokenUsageSummary {
  inputTokens: number
  cachedInputTokens: number
  outputTokens: number
  reasoningOutputTokens: number
  totalTokens: number
}

export declare function toonEncode(value: JsonValue): string

export interface TuiExitInfo {
  tokenUsage: TokenUsageSummary
  conversationId?: string
  updateAction?: UpdateActionInfo
}

export interface TuiRequest {
  prompt?: string
  images?: Array<string>
  model?: string
  oss?: boolean
  sandboxMode?: string
  approvalMode?: string
  resumeSessionId?: string
  resumeLast?: boolean
  resumePicker?: boolean
  fullAuto?: boolean
  dangerouslyBypassApprovalsAndSandbox?: boolean
  workingDirectory?: string
  configProfile?: string
  configOverrides?: Array<string>
  addDir?: Array<string>
  webSearch?: boolean
  linuxSandboxPath?: string
  baseUrl?: string
  apiKey?: string
  reasoningEffort?: string
  reasoningSummary?: string
}

export interface TuiTestRequest {
  width: number
  height: number
  viewport: TuiTestViewport
  lines: Array<string>
}

export declare function tuiTestRun(req: TuiTestRequest): Array<string>

export interface TuiTestViewport {
  x: number
  y: number
  width: number
  height: number
}

export interface UpdateActionInfo {
  kind: string
  command: string
}

export declare const enum WidgetType {
  Text = 0,
  Chat = 1,
  Terminal = 2,
  ProgressBar = 3,
  StatusLine = 4,
  Table = 5,
  FileTree = 6,
  Markdown = 7
}

export interface WorkspaceWriteOptions {
  networkAccess?: boolean
  writableRoots?: Array<string>
  excludeTmpdirEnvVar?: boolean
  excludeSlashTmp?: boolean
}
