/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function callToolBuiltin(token: string, invocation?: JsToolInvocation): Promise<NativeToolResponse>

export declare function clearRegisteredTools(): void

export declare function cloudTasksApply(taskId: string, diffOverride?: string | undefined | null, baseUrl?: string | undefined | null, apiKey?: string | undefined | null): Promise<string>

export declare function cloudTasksApplyPreflight(taskId: string, diffOverride?: string | undefined | null, baseUrl?: string | undefined | null, apiKey?: string | undefined | null): Promise<string>

export declare function cloudTasksCreate(envId: string, prompt: string, gitRef?: string | undefined | null, qaMode?: boolean | undefined | null, bestOfN?: number | undefined | null, baseUrl?: string | undefined | null, apiKey?: string | undefined | null): Promise<string>

export declare function cloudTasksGetDiff(taskId: string, baseUrl?: string | undefined | null, apiKey?: string | undefined | null): Promise<string>

export declare function cloudTasksList(envFilter?: string | undefined | null, baseUrl?: string | undefined | null, apiKey?: string | undefined | null): Promise<string>

export declare function compactThread(req: RunRequest): Promise<Array<string>>

/** SSE event for a single assistant message output item. */
export declare function evAssistantMessage(id: string, text: string): string

/** SSE event for a completed response with a specific id. */
export declare function evCompleted(id: string): string

/** SSE event for a function call. */
export declare function evFunctionCall(callId: string, name: string, args: string): string

/** SSE event for a created response with a specific id. */
export declare function evResponseCreated(id: string): string

export interface JsApprovalRequest {
  type: string
  details?: JsonValue
}

export interface JsToolInterceptorContext {
  invocation: JsToolInvocation
  token: string
}

export declare function clearRegisteredTools(): void

export interface JsToolInvocation {
  callId: string
  toolName: string
  arguments?: string
  input?: string
}

export interface NativeToolInfo {
  name: string
  description?: string
  parameters?: JsonValue
  strict?: boolean
  supportsParallel?: boolean
}

export interface NativeToolResponse {
  output?: string
  success?: boolean
  error?: string
}

export declare function registerApprovalCallback(handler: (request: JsApprovalRequest) => boolean | Promise<boolean>): void

export declare function registerTool(info: NativeToolInfo, handler: (call: JsToolInvocation) => NativeToolResponse | Promise<NativeToolResponse>): void

export declare function registerToolInterceptor(toolName: string, handler: (context: JsToolInterceptorContext) => NativeToolResponse | Promise<NativeToolResponse>): void
export declare function registerTool(info: NativeToolInfo, handler: (arg: JsToolInvocation) => NativeToolResponse): void

export interface RunRequest {
  prompt: string
  threadId?: string
  images?: Array<string>
  model?: string
  oss?: boolean
  sandboxMode?: string
  approvalMode?: string
  workspaceWriteOptions?: WorkspaceWriteOptions
  /** Enable native review mode (mirrors CLI review flow). Optional. */
  reviewMode?: boolean
  /** Optional user-facing hint for the review flow. */
  reviewHint?: string
  sandboxMode?: string
  workingDirectory?: string
  skipGitRepoCheck?: boolean
  outputSchema?: JsonValue
  baseUrl?: string
  apiKey?: string
  linuxSandboxPath?: string
  fullAuto?: boolean
}

export declare function runThread(req: RunRequest): Promise<Array<string>>

export declare function runThreadStream(req: RunRequest, onEvent: (err: unknown, eventJson?: string) => void): Promise<void>

/** Create an SSE stream body from a list of event JSON strings. */
export declare function sse(events: Array<string>): string

export interface WorkspaceWriteOptions {
  networkAccess?: boolean
  writableRoots?: Array<string>
  excludeTmpdirEnvVar?: boolean
  excludeSlashTmp?: boolean
}
export declare function runThreadStream(req: RunRequest, onEvent: ((err: Error | null, arg: JsonValue) => any)): Promise<void>
