import { createRequire } from "node:module";

import type { SandboxMode } from "./threadOptions";

export type NativeRunRequest = {
  prompt: string;
  threadId?: string;
  images?: string[];
  model?: string;
  sandboxMode?: SandboxMode;
  workingDirectory?: string;
  skipGitRepoCheck?: boolean;
  outputSchema?: unknown;
  baseUrl?: string;
  apiKey?: string;
  linuxSandboxPath?: string;
  fullAuto?: boolean;
  reviewMode?: boolean;
  reviewHint?: string;
};

export type NativeBinding = {
  runThread(request: NativeRunRequest): Promise<string[]>;
  runThreadStream(
    request: NativeRunRequest,
    onEvent: (err: unknown, eventJson?: string) => void,
  ): Promise<void>;
  clearRegisteredTools(): void;
  registerTool(info: NativeToolInfo, handler: (call: NativeToolInvocation) => Promise<NativeToolResult> | NativeToolResult): void;
};

export type NativeToolInfo = {
  name: string;
  description?: string;
  parameters?: unknown;
  strict?: boolean;
  supportsParallel?: boolean;
};

export type NativeToolInvocation = {
  toolName: string;
  callId: string;
  arguments?: string;
  input?: string;
};

export type NativeToolResult = {
  output?: string;
  success?: boolean;
  error?: string;
};

let cachedBinding: NativeBinding | null | undefined;

export function getNativeBinding(): NativeBinding | null {
  if (cachedBinding !== undefined) {
    return cachedBinding;
  }

  const require = createRequire(import.meta.url);

  // For sdk/native: load the NAPI binding from the package root
  // The index.js is auto-generated by napi-rs and loads the .node file
  try {
    const binding: NativeBinding = require("../index.js");
    cachedBinding = binding;
    return cachedBinding;
  } catch (error) {
    console.warn("Failed to load native NAPI binding:", error);
    cachedBinding = null;
    return cachedBinding;
  }
}
